Parameters:
  SageMakerNotebookName:
    Type: String
    Description: Name of the Sagemaker Notebok
    Default: DeployEndpoints

Resources:  
  CodeRepository:
    Type: AWS::SageMaker::CodeRepository
    Properties:
      GitConfig:
          RepositoryUrl: https://github.com/Sypek/llm-qa-2023

  NotebookInstance:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      NotebookInstanceName: !Ref SageMakerNotebookName
      InstanceType: ml.t3.2xlarge
      RoleArn: !GetAtt SagemakerRole.Arn
      DefaultCodeRepository: !GetAtt CodeRepository.CodeRepositoryName

  SagemakerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "CustomSagemakerRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - sagemaker.amazonaws.com
            Action:
              - 'sts:AssumeRole'

Outputs:
  SageMakerNotebookURL:
    Description: SageMaker Notebook URL
    Value: !Join
      - ''
      - - !Sub 'https://console.aws.amazon.com/sagemaker/home?region=${AWS::Region}#/notebook-instances/openNotebook/'
        - !GetAtt NotebookInstance.NotebookInstanceName
        - '?view=classic'