Parameters:
  DevRoleArn:
    Type: String
    Description: ARN of the role that is going to be added in AssumeRolePolicyDocument for DataUploaderRole

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket

  DataUploaderRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: data-uploader-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref DevRoleArn
            Action: sts:AssumeRole
      Policies:
        - PolicyName: s3-access-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource: 
                  - !Sub "arn:aws:s3:::${S3Bucket}/*"
                  - !Sub "arn:aws:s3:::${S3Bucket}"

Outputs:
  S3BucketName:
    Description: Name of the created bucket
    Value: !Ref S3Bucket

  DataUploaderRoleName:
    Description: Name of the created role
    Value: !Ref DataUploaderRole

  DataUploaderRoleArn:
    Description: Arn of the created role
    Value: !GetAtt DataUploaderRole.Arn