Parameters:
  DevRoleArn:
    Type: String
    Description: ARN of the role that is going to be added in AssumeRolePolicyDocument for DataUploaderRole

  SageMakerNotebookName:
    Type: String
    Description: Name of the Sagemaker Notebok
    Default: DeployEndpoints

  SageMakerEndpointEmbeddings:
    Type: String
    Description: Name of the SageMaker DeployEndpoints
    Default: 'LLM-EMBEDDINGS'

  SageMakerEndpointGenerative:
    Type: String
    Description: Name of the SageMaker DeployEndpoints
    Default: 'LLM-GENERATIVE'

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket

  DataUploaderRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: data-uploader-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref DevRoleArn
            Action: sts:AssumeRole
      Policies:
        - PolicyName: s3-access-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource: 
                  - !Sub "arn:aws:s3:::${S3Bucket}/*"
                  - !Sub "arn:aws:s3:::${S3Bucket}"

  CodeRepository:
    Type: AWS::SageMaker::CodeRepository
    Properties:
      GitConfig:
        RepositoryUrl: https://github.com/Sypek/llm-qa-2023

  NotebookInstance:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      NotebookInstanceName: !Ref SageMakerNotebookName
      InstanceType: ml.t3.2xlarge
      RoleArn: !GetAtt SagemakerRole.Arn
      DefaultCodeRepository: !GetAtt CodeRepository.CodeRepositoryName

  SagemakerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "CustomSagemakerRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - sagemaker.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: cloud-formation-access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackEvents
                  - cloudformation:DescribeStackResource
                  - cloudformation:DescribeStackResources
                  - cloudformation:GetTemplate
                  - cloudformation:ListStackResources
                Resource:
                  - !Sub 'arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${AWS::StackName}/*'
                  - !Sub 'arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${AWS::StackName}'
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - !Sub 'arn:aws:s3:::${S3Bucket}'
                  - !Sub 'arn:aws:s3:::${S3Bucket}/*'

Outputs:
  S3BucketName:
    Description: Name of the created bucket
    Value: !Ref S3Bucket

  DataUploaderRoleName:
    Description: Name of the created role
    Value: !Ref DataUploaderRole

  DataUploaderRoleArn:
    Description: Arn of the created role
    Value: !GetAtt DataUploaderRole.Arn

  AWSRegion:
    Value: !Ref 'AWS::Region'

  StackName:
    Value: !Ref 'AWS::StackName'

  SageMakerEndpointEmbeddings:
    Value: !Ref SageMakerEndpointEmbeddings

  SageMakerEndpointGenerative:
    Value: !Ref SageMakerEndpointGenerative

  SageMakerNotebookURL:
    Description: SageMaker Notebook URL
    Value: !Join
      - ''
      - - !Sub 'https://console.aws.amazon.com/sagemaker/home?region=${AWS::Region}#/notebook-instances/openNotebook/'
        - !GetAtt NotebookInstance.NotebookInstanceName
        - '?view=classic'